### ISSUE TITLE
Differences between this and Xash3D (SDL fork)?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [Sh1ft0x0EF/OpenGoldSrc#2]
Hey!
I stumbled across this branch and I was wondering what the difference between this and Xash3D (Specifically SDL fork, since that is cross-platform).

Thanks. c:

**Comment by Sh1ft0x0EF** [comment]
Xash is C-only. It was built using codebases of Id Techs 1-3 + Darkplaces. There is no support for C++ interfaces of GS (his module factories). Yes, it can load and interact with GS' game dlls, but overall architecture is absolutely different. Xash has a support for Quake maps which just causes issues with proper work of GS maps.

OGS is meant to be closer to GS. The target is to recreate GS (4554 for now) itself with some of his modules and provide an ability to link OGS with original GS modules

**Comment by CrusoeDaWolf** [comment]
Alright. When do you have an ETA for a release? I could do testing and such. This sounds like an interesting project. c:

**Comment by Sh1ft0x0EF** [comment]
Release? Who knows, it's a really long way to release from current point of view
Some working prototype with basic graphics support that will allow to fly around the map - I hope to achieve that in next month

**Comment by SourcePowered** [comment]
Sir, do you want to support VGUI or VGUI2?
And CS, and any other GoldSource's Mods?

**Comment by Sh1ft0x0EF** [comment]
Yep
